---
- name: test if node_red_working_directory is set correctly
  assert:
    that:
      - node_red_working_directory is defined
    quiet: yes

- name: test if node_red_user_name is set correctly
  assert:
    that:
      - node_red_user_name is defined
    quiet: yes

- name: test if node_red_group_name is set correctly
  assert:
    that:
      - node_red_group_name is defined
    quiet: yes
